---
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:7.2-browsers
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install php7.2-xdebug -y
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "composer.json" }}
            - v2-dependencies-
      - run: composer install --no-interaction
      - save_cache:
          key: v2-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: mkdir -p build/logs
      - run: XDEBUG_MODE=coverage ./vendor/bin/phpunit -c phpunit.xml
      - run: ./vendor/bin/php-coveralls -v

workflows:
  build_and_test:
    jobs:
      - build
