jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - run: sudo apt update
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install --dev --no-interaction
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: mkdir -p build/logs
      - run: XDEBUG_MODE=coverage ./vendor/bin/phpunit -c phpunit.xml
      - run: ./vendor/bin/php-coveralls -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
